### ISSUE TITLE
Personalized video dimension in matrix

### ISSUE THREAD

**Issue by Ziowebbo** [grigory-lobkov/rtsp-camera-view#10]
Hi, 
it would be great if the software had the possibility to resize the Video in the matrix to create (if user need it) a camera view in different dimension. This will allow to have a focus on a camera and have others smaller.
Try to add an image for example.
![38257663-ed3059ca-3760-11e8-8850-b294a190c5b2](https://user-images.githubusercontent.com/38044432/41960922-47ed0b06-79f1-11e8-8a77-2695cd3ccaae.png)

**Comment by grigory-lobkov** [comment]
Thank you for this idea, I will try to do it in summer.
The other big enhancement is to move to VLC 3... But I think, I need to release something first :)

**Comment by grigory-lobkov** [comment]
Please, test it in 1.0.0.6
https://github.com/grigory-lobkov/rtsp-camera-view/releases
I think, this will be a release candidate.

**Comment by Ziowebbo** [comment]
You did it!! Is working GREAT and flawlessy Grigory!!!!! 
Just a little thing, The TEXT: when you Join the "cells" the video is bigger and also the text, but it risk to be too large respect of the other text's video.
Is possible to have text fixed to the dimension we choose in the settings?

**Comment by grigory-lobkov** [comment]
Thanks. Done. Re-download the 1.0.0.6 :)

**Comment by Ziowebbo** [comment]
Did it and is perfect, thanks!!! Gonn write you about the mail alert...

2018-07-17 20:09 GMT+02:00 Grigory Lobkov <notifications@github.com>:
