### ISSUE TITLE
installation problem.

### ISSUE THREAD

**Issue by BalarajAdappa** [grigory-lobkov/rtsp-camera-view#12]
Hi @grigory-lobkov  i have already installed vlc 2.1.5 in my pc.   when i install latest beta version its showing me error that "install vlc 2.1.5 " i followed instructions and installed vlc then i tried to install your rtsp player still getting same [error.]
(url
![image](https://user-images.githubusercontent.com/34572218/42090215-2b4ef40e-7bbe-11e8-9d48-b95fe03b4696.png)
)

**Comment by grigory-lobkov** [comment]
Thank you for using my app!
It's a pitty, you met error before use :(

Please, reinstall VLC:
1) install it to default folder;
2) be sure, "ActiveX Web-module" is selected.

In beta version I tried to make errors more detailed.

**Comment by grigory-lobkov** [comment]
Oh, you've tried Beta!
I see the detailed error message "Check your VLC version is 2.1.x"

What version of VLC you've installed ?
For now, my app supports only VLC 2.1.3 / 2.1.5.

**Comment by BalarajAdappa** [comment]
Hi @grigory-lobkov  i have tried both vlc 2.1.3 and vlc 2.1.5 also.

**Comment by grigory-lobkov** [comment]
Please, try to use installation version (not portable) of Release.
Try to get, what additional products it will install.
May be it will be "Microsoft Visual C++ Redistributable", or something like this.
Or "Microsoft framework".

And say me, what installed/happened, please...
You can take a screenshots, if possible...

**Comment by grigory-lobkov** [comment]
@BalarajAdappa how does it going?
I've released [1.0.0.6](https://github.com/grigory-lobkov/rtsp-camera-view/releases/tag/1.0.0.5)
Please, check it out!
