### ISSUE TITLE
Is it possible to Save stream to disk.

### ISSUE THREAD

**Issue by BalarajAdappa** [grigory-lobkov/rtsp-camera-view#16]
Hi @grigory-lobkov  i am curioused about  knowing is there any possibility to store stream to system memory? . 

thanks regards
Balaraj

**Comment by grigory-lobkov** [comment]
Unfortunately, No.
Not for now. Save stream/movement detection realized in several popular free software:
iSpy, Milestone Systems, ZoneMinder.
I already adviced it to you...

It's a big work, different interfaces. Maybe later.
Please, try these products and say, why you don't like it...

**Comment by BalarajAdappa** [comment]
thank you for your response i'll check those. thank you @grigory-lobkov
