### ISSUE TITLE
When network is bit slow will not connect to stream server.

### ISSUE THREAD

**Issue by BalarajAdappa** [grigory-lobkov/rtsp-camera-view#17]
Hi @grigory-lobkov  sorry for this , when my network is bit slow stream will play in vlc player but stream will not play in rtsp-camera-view ,i could do any work arounds please suggest me.

thanks regards
Balaraj.

**Comment by grigory-lobkov** [comment]
Try to increase priority of rtsp-camera-view
(by command line parameters, or by Windows Task manager)
Try to close all programs, using network: torrent server/client, download managers, e.t.c.

Are you using the same connect strings to open camera streams?
If you are playing the main stream, try to find substream and check it out.
