### ISSUE TITLE
DLL files are missing in sources of latest version

### ISSUE THREAD

**Issue by BalarajAdappa** [grigory-lobkov/rtsp-camera-view#18]
Hi @grigory-lobkov  these .DLL   are missing in this latest released source project.

![rtsp camera view](https://user-images.githubusercontent.com/34572218/43624086-bcb32938-9702-11e8-834e-5cb5caece5bf.png)

**Comment by grigory-lobkov** [comment]
They must be compiled/created by your C#.
You have to install NuGet packages first.
