### ISSUE TITLE
Always getting an error VLC 2.1.5 not found

### ISSUE THREAD

**Issue by ivandevel** [grigory-lobkov/rtsp-camera-view#19]
Windows 7 Pro. Performed full installation of VLC 2.1.5 32 bit. Always got an error:
![error](https://user-images.githubusercontent.com/8140949/44631920-400e6180-a98c-11e8-9122-3ba5399029d9.jpg)

**Comment by grigory-lobkov** [comment]
Thank you for interesting in my project!

What version of rtsp-camera-view have you installed ?
Try to install "[RTSP.mosaic.VLC.player.0.1.4.2.installation.zip](https://github.com/grigory-lobkov/rtsp-camera-view/releases/tag/v0.1.4)" to resolve dependencies.
And then start a portable version.
Or try a previous release.

P.S. Sorry for long answer - I was on vacation :)
