### ISSUE TITLE
Help regarding RTSP Connection Re-Establishment when there are interrupts.

### ISSUE THREAD

**Issue by BalarajAdappa** [grigory-lobkov/rtsp-camera-view#22]
Hi @grigory-lobkov  i wanted help regarding connection re-establishment, 
scenario1- streaming is happening , suppose there is network loss for about few minutes our stream player will loss connection and then network works normal then Player should Re-establish connection to stream server ,
scenario2-someone accidentally  unplug network cable , and plug back then player should Re-establish connection.  

please suggest what is the improvements we can do.

**Comment by grigory-lobkov** [comment]
please, check this out, it should already work.

**Comment by dinesh1218** [comment]
@grigory-lobkov I'm also in need of same scenario, While using RTSP, the connection needs to be re-established when the network is recovered from failure. Can you please help me with this?

**Comment by grigory-lobkov** [comment]
It's done already!
Just wait a little (up to 10 minutes), and connection will reestablish!

P.S. If you tried and waited some time, and the camera was not recovered, then, say, what are you doing step-by-step.
P.P.S. you can link to BalarajAdappa scenarios.

**Comment by dinesh1218** [comment]
@grigory-lobkov Thanks for your reply. It's automatically reconnects once is network is back.

**Comment by grigory-lobkov** [comment]
And if network will disconnect several times, it's not reconnected?

**Comment by dinesh1218** [comment]
@grigory-lobkov Yeah, I tried disconnecting the network a couple of times, it's getting reconnected.
