### ISSUE TITLE
Show options

### ISSUE THREAD

**Issue by Reddds** [grigory-lobkov/rtsp-camera-view#24]
Было бы хорошо добавить настройки показа поверх остальных окон (чтобы панель задач не уменьшала видимую область) и настройку, скрывающую заголовок окна.

It would be nice to add settings: display on top of other windows (so that the taskbar does not reduce the visible area) and settings that hide the window title.

**Comment by grigory-lobkov** [comment]
Пожалуйста, попробуйте параметр командной строки fullscreen=1 / fullscreen
В контекстом меню есть опция "На весь экран". Может быть это подойдет?...

Please, try command line parameter "fullscreen=1" / "fullscreen"
There's option in context menu "Full screen". Does it suits you?...

**Comment by grigory-lobkov** [comment]
Can I close it ?
Does it suits you ?
