### ISSUE TITLE
Mail aler config nor respecting locale

### ISSUE THREAD

**Issue by Fernando-Kiernan** [grigory-lobkov/rtsp-camera-view#26]
The mail alert config screen is not showing the translated messages.

Regards

**Comment by grigory-lobkov** [comment]
Wow! It's funny!
fixed in [1.0.2](https://github.com/grigory-lobkov/rtsp-camera-view/releases/tag/v1.0.2) release
Can you check this out ? :)

**Comment by Fernando-Kiernan** [comment]
Ye,s now it's fixed.

Thank you!!
