### ISSUE TITLE
7 camera limit?

### ISSUE THREAD

**Issue by shwnchr** [grigory-lobkov/rtsp-camera-view#31]
Similar to Issue #9 (closed)

I can't ever seem to get more than 7 cameras to display at one time in my 3x3 matrix.

When the program starts, it attempts to load all 9 cameras but 2 of them fail. Once I close one of the successfully loaded cameras and wait a short while, one of the failed cameras will load successfully. If I then re-add the closed camera, it will fail to load.

**Comment by grigory-lobkov** [comment]
Yes, it's known problem.
The solution will be closing issue #2 by smbd.
Have no time for now, sorry.
