### ISSUE TITLE
VLC can not be found by program on Windows 10

### ISSUE THREAD

**Issue by yxm0513** [grigory-lobkov/rtsp-camera-view#35]
VLC was installed with default path without any issue, and then run the program, still get an error as :

![screen](https://github.com/yxm0513/test/blob/master/a.png?raw=true)

**Comment by PerpendicularApps** [comment]
Not just in 10, but in Seven too.

**Comment by gomezpt** [comment]
No compatibility with VLC 3.x.x ?

**Comment by RuStrannik** [comment]
Just in case it might work for you:
https://stackoverflow.com/questions/59180160/mosaic-of-rtsp-streams-vlc-3-0-8

**Comment by grigory-lobkov** [comment]
Hi, guys.
You have to install VLC 2.1.5 with "Web plugins" option in installer selected.
![image](https://user-images.githubusercontent.com/36440722/80284460-08932200-8738-11ea-87de-49bafc830693.png)


There's no compatibility with vlc 3.x for now, sorry.
