### ISSUE TITLE
Upgrade libvlc and use modern .NET wrapper

### ISSUE THREAD

**Issue by mfkl** [grigory-lobkov/rtsp-camera-view#4]
Hi @grigory-lobkov ,

Good job with your app! I have 2 suggestions, let me know if you agree:

- You should use libvlc version 3+. 2.x is getting old and 3.x has more bugfixes and features, and less security issues. You can also get it from nuget [here](https://www.nuget.org/packages/VideoLAN.LibVLC.Windows). Please consider it.
- I see you're using an ActiveX module to access libvlc from .NET code. This isn't the recommended way to do things, even if I can understand it works for you, as this module is not maintained (that I know of). Please consider using [Vlc.DotNet](https://github.com/ZeBobo5/Vlc.DotNet/) which is maintained by the community and more up to date. 

What do you think?

**Comment by grigory-lobkov** [comment]
Thank you, @mfkl, you noticed my work.

Yes, I'm agree.

Maybe, I'll have a commercial version with additional functionality. Can you advice, which of your suggestions is better to learn/introduce in this way? ... and Can you give a c# example/instructions, I will note it.
