### ISSUE TITLE
how to connect to multicast rtsp camera ?

### ISSUE THREAD

**Issue by BalarajAdappa** [grigory-lobkov/rtsp-camera-view#5]
Hi @grigory-lobkov  i'm using your stream viewer, thanks is not enough to say you, i can connect to unicast stream camera using your app, now i want to receive multiicast stream , what changes should i  do to get it done?? help would be appreciated.

**Comment by grigory-lobkov** [comment]
Good day, @BalarajAdappa 

Thank you for using my app. Are you using Beta, or Release?

You can use rtsp-camera-view'er with any string, you provide to vlc Media -> Open Network Stream
![Open Network Stream](https://user-images.githubusercontent.com/36440722/40304946-f5cb0e3c-5d11-11e8-867a-91f0cfc0ab54.png)

You need to find the url string to connect your camera multicast port and try to open in VLC first.

The first instruction, I've found is for [Dahua NVR](https://dahuawiki.com/NVR/Recording_Setup/Multicast_Setup)

**Comment by BalarajAdappa** [comment]
Hi @grigory-lobkov   i have tried it but i could not receive multicast stream . the unicast adrress id= rtsp://192.168.1.13:554/JPEG 90000 and multicast ip address is=rtsp://@224.0.0.10:554/JPEG 90000 when i connect to unicast connectoin will establish and data will be sent to multicast group, (i can see data in wireshark) but when i try to connect to multicast address using vlc it is not working

**Comment by grigory-lobkov** [comment]
Multicast is used to decrease camera CPU load, when a lot of clients connected. I don't know about others, but it seems, your camera does not generate multicast until unicast is used by somebody. Why don't you use unicast, if you are only one observer? ...

BTW, maybe it's better to use not JPEG stream, because it produces high network load.

Have you tried to use unicast address in vlc?

**Comment by BalarajAdappa** [comment]
Hi @grigory-lobkov  i have tried unicast its working fine, i want multiple observer to see my stream i want to try for multicast.

**Comment by grigory-lobkov** [comment]
1
Maybe, you have one client, you sure, he will be always connected - just give him a unicast address, multicast - for others

2
Search in camera web-console for option "multicast always"

3
Ask camera vendor for "multicast always" ability

**Comment by BalarajAdappa** [comment]
Hi @grigory-lobkov  May i know this application is available for android platform like Android TV or Phone??

Thanks .

**Comment by grigory-lobkov** [comment]
I have seen a lot of programs on google play ([rtsp view](https://play.google.com/store/search?q=rtsp%20view&c=apps), [ip camera view](https://play.google.com/store/search?q=ip%20camera%20view&c=apps)), try it. I've used only programs for one camera.
Do you have NVR?
You can ask NVR-vendor for Android software to connect it.

I'm also using free [ONVIFER](https://play.google.com/store/apps/details?id=net.biyee.onvifer) for one-camera view and PTZ-control. But on the pictures I've found multi-camera view. You can try this also.

**Comment by grigory-lobkov** [comment]
Please, check out a new [beta 1.0.0.5](https://github.com/grigory-lobkov/rtsp-camera-view/releases/tag/1.0.0.5) !

**Comment by BalarajAdappa** [comment]
@grigory-lobkov thanks and is it possible to dump stream into pc or external disk? if possible please guide me.

thanks regards
Balaraj adappa

**Comment by grigory-lobkov** [comment]
For now I only think about necessity of this function, because this product called "camera view", but not record, not register. And it's quite difficult to do it good and conveniently.

**Comment by grigory-lobkov** [comment]
You can try http://www.ispyconnect.com/download-agent.aspx
and https://iss.ru/upload/securos-lite-9.6-R1.zip (maybe only russian language)
for this purposes.

And write me your opinion about it, please...

**Comment by BalarajAdappa** [comment]
Thank you @grigory-lobkov  i will check  and tell you my opinion.
