### ISSUE TITLE
How do I disable the hints?

### ISSUE THREAD

**Issue by HayStax** [grigory-lobkov/rtsp-camera-view#6]
I'm using beta 1.0.0.4.

I also noticed that when putting the window into a second screen on the right and enabling full screen, the button to open the panel is sticking out into the left screen.

**Comment by grigory-lobkov** [comment]
Thank's again for testing my app.

I designed the smart hints: they are shown, if user don't do something for a long time. I will increase this time. Maybe I should change show-conditions for some hint? Can you explain, what hint disturbs you and why?

"open panel button sticks wrong screen" - will check this out, thank you.

**Comment by grigory-lobkov** [comment]
"open panel button sticks wrong screen"
fixed in [1.0.0.6](https://github.com/grigory-lobkov/rtsp-camera-view/releases)
... I hope :)
Please, try it!
P.S. Uploaded just now!
