### ISSUE TITLE
Grey Tags showing after trying the latest beta

### ISSUE THREAD

**Issue by IraqiNinja** [grigory-lobkov/rtsp-camera-view#8]
![image](https://user-images.githubusercontent.com/40210814/41303070-380d4e70-6e3a-11e8-80d2-c13c86ec038e.png)

This keeps showing on the new Beta version, any way to get rid of it?
{name} LOST link
{name} recovered link

Working amazing other than that.

Thanks a lot.

**Comment by grigory-lobkov** [comment]
Thank you for testing my program!
I will fix it in new beta!

Sorry, for such a blunder!

You give me the strength to go forward.

**Comment by IraqiNinja** [comment]
Any way i can donate to your project? , I am new here, sorry if its a dumb question :)

**Comment by grigory-lobkov** [comment]
Finances make us feel free. It would be great, if I can drop my main job and do only the things I like - make products helping people.

When you pay, I feel responsibility to do my best! I have updated the [wiki page](https://github.com/grigory-lobkov/rtsp-camera-view/wiki)

Donates are welcome of cause!

**Comment by grigory-lobkov** [comment]
Please, check out this issue in new [beta 1.0.0.5](https://github.com/grigory-lobkov/rtsp-camera-view/releases/tag/1.0.0.5)

**Comment by grigory-lobkov** [comment]
[1.0.0.6](https://github.com/grigory-lobkov/rtsp-camera-view/releases/tag/1.0.0.5) released!
Waiting for your opinion...
